### ISSUE TITLE
Share fingerprint of the repository in the URL

### ISSUE THREAD

**Issue by parmegv** [2br-2b/Fdroid-repo#1]
Hi,

 Thank you very much for setting up this F-Droid repository.

 It would be great if you could add some security details for us to make sure we are actually using your repository and nobody is tampering with it. In a quick search I couldn't find documentation on how to obtain the fingerprint, but it you can look at [this list](https://forum.f-droid.org/t/known-repositories/721) to see how they look like.

 Thanks again,

Rafa

**Comment by 2br-2b** [comment]
Hi,

I realized I had put the fingerprint in the qr code, but not in the links :-)

Thanks!

Fixed with 774bf9e
